// info about function names taken from
// https://git.zx2c4.com/wireguard-nt/tree/example/example.c

#include "wireguard.h"

WIREGUARD_CREATE_ADAPTER_FUNC WireGuardCreateAdapter;
WIREGUARD_OPEN_ADAPTER_FUNC WireGuardOpenAdapter;
WIREGUARD_CLOSE_ADAPTER_FUNC WireGuardCloseAdapter;
WIREGUARD_GET_ADAPTER_LUID_FUNC WireGuardGetAdapterLUID;
WIREGUARD_GET_RUNNING_DRIVER_VERSION_FUNC WireGuardGetRunningDriverVersion;
WIREGUARD_DELETE_DRIVER_FUNC WireGuardDeleteDriver;
WIREGUARD_SET_LOGGER_FUNC WireGuardSetLogger;
WIREGUARD_SET_ADAPTER_LOGGING_FUNC WireGuardSetAdapterLogging;
WIREGUARD_GET_ADAPTER_STATE_FUNC WireGuardGetAdapterState;
WIREGUARD_SET_ADAPTER_STATE_FUNC WireGuardSetAdapterState;
WIREGUARD_GET_CONFIGURATION_FUNC WireGuardGetConfiguration;
WIREGUARD_SET_CONFIGURATION_FUNC WireGuardSetConfiguration;